# Generated by Django 2.2.7 on 2019-11-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentence',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
