# Generated by Django 2.2.7 on 2019-11-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191125_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='corword',
            name='sym',
            field=models.BooleanField(default=False),
        ),
    ]
