# Generated by Django 2.2.7 on 2019-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_corword_sym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corword',
            name='sym',
        ),
        migrations.AddField(
            model_name='word',
            name='sym',
            field=models.BooleanField(default=False),
        ),
    ]
